[package]
name = "arangors"
version = "0.3.0"
edition = "2018"
authors = ["Guoli Lyu <guoli-lv@hotmail.com>"]
readme = "README.md"
license = "MIT"
description = "Rust driver for ArangoDB"
repository = "https://github.com/fMeow/arangors"
documentation = "https://docs.rs/arangors"
keywords = ["nosql", "database", "client", "driver", "arangoDB"]

[package.metadata.docs.rs]
all-features = true
features = [
    "cluster",
    "enterprise",
    "mmfiles",
    "rocksdb",
    "reqwest_async"
]

[badges]
travis-ci = { repository = "fMeow/arangors", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["rocksdb", "reqwest_async"]
blocking = ["maybe-async/is_sync"]
reqwest_async = ["reqwest"]
reqwest_blocking = ["reqwest/blocking", "blocking"]

cluster = []
enterprise = []
mmfiles = []
rocksdb = []

[dependencies]
async-trait = "0.1"
base64 = "0.12"
failure = "0.1"
http = "0.2"
log = "0.4"
maybe-async = "0.1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"

reqwest  = { version = "0.10", features = ["gzip", "json"], optional = true }

[dev-dependencies]
env_logger = "0.7.1"
pretty_assertions = "0.6.1"
dotenv = "0.15.0"
regex = "1.3.7"
tokio = { version = "0.2.18", features = ["macros", "rt-core"]}
